arb-dir: lib/src/localization
template-arb-file: app_en.arb
output-class: AppLocalizations
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
